export const mockArtists = [
  {
    id: 1,
    name: "Ariana Silver",
    category: "Singer",
    location: "Mumbai",
    priceRange: "₹30K - ₹50K",
    onboarded:true,
  },
  {
    id: 2,
    name: "DJ Shadow",
    category: "DJ",
    location: "Bangalore",
    priceRange: "₹20K - ₹40K",
    onboarded:true,
  },
  {
    id: 3,
    name: "Rhythm Souls",
    category: "Dancer",
    location: "Delhi",
    priceRange: "₹25K - ₹35K",
    onboarded:true,
  },
  {
    id: 4,
    name: "Talksmith",
    category: "Speaker",
    location: "Hyderabad",
    priceRange: "₹40K - ₹60K",
    onboarded:true,
  },
  {
    id: 5,
    name: "Steve",
    category: "Guitarist",
    location: "Mumbai",
    priceRange: "₹40K - ₹60K",
    onboarded:true,
  },
  {
    id: 6,
    name: "Dian",
    category: "Paintist",
    location: "Delhi",
    priceRange: "₹20K - ₹40K",
    onboarded:true,
  },
  {
    id: 7,
    name: "Slackss",
    category: "Stand-Up Comedian",
    location: "Mussorie",
    priceRange: "₹20K - ₹35K",
    onboarded:true,
  },
  {
    id: 8,
    name: "Tian",
    category: "Photographer",
    location: "Mysore",
    priceRange: "₹30K - ₹50K",
    onboarded:true,
  },
];
